### ISSUE TITLE
User Story: Homepage

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#10]
As a **User**, I can visit the homepage so I can understand the content of the application

**Acceptance Criteria:**
1. Homepage html exists 
2. Homepage is styled and fully responsive 
3. Home page contains all relevant information

**Tasks**
- [x] Create homepage html
- [x] Create styles.css
- [x] Style the page so its fully responsive
- [x] Represent the content of the application
- [x] Represent the marketing copy of the website
