### ISSUE TITLE
User Story: Site Navigation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#11]
As a **User**, I can easily navigate the website so that I can view all content

**Acceptance Criteria:**
1. A navigation bar exists
2. Navigations links are all working  
3. The navigation theme is consistant with the website

**Tasks**
- [ ] Create a header/nav bar
- [ ] Style the header/navbar
- [ ] Link all pages to the navbar
- [ ] Ensure proper UI feedback
