### ISSUE TITLE
User Story: User Data Input

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#19]
As a User, I can choose from food, drinks, and activity options so that I can plan a fun and enjoyable experience.

**Acceptance Criteria:**
1. The options page must include categories for food, drinks, and activities.
2 .Each category must have four options listed.
3. The user must be able to select one option from each category.
4. The options provided should cover a variety of interests and preferences.

**Tasks**
- [x]  Create a layout for the options page.
- [x]  Populate the food category with six options.
- [x]  Populate the drinks category with six options.
- [x]  Populate the activity category with six options.
- [x]  Implement functionality for the user to select one option from each category.
- [x]  Test the options page to ensure it functions correctly.
- [x]  Make any necessary revisions based on user feedback.

**Comment by DarrachBarneveld** [comment]
User data is input
