### ISSUE TITLE
User Story: Backend API

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#21]
As a **developer**, I can set up a backend endpoint so that I can store sensitive data and fetch information from the serverside

**Tasks**
- [x] 1. Set up a backend folder
- [x] 2. Create API endpoints
- [x] 3. Store sensitive keys
- [x] 4. Create django rest framework apiviews etc

**Comment by DarrachBarneveld** [comment]
Super excited for this!

**Comment by DarrachBarneveld** [comment]
Backend API merged into main.
