### ISSUE TITLE
User Story: Locations Near Me

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#23]
As a **User**, I can find locations near me based off the AI recommendation 

**Acceptance Criteria:**
1. After recommendation is chosen places near me are rendered
2. The places show me where I can find
3. This feature is only allowed if location services are on

**Tasks**
- [x] Create a fetch call to google places api
- [x]  Use text search in coalition with location proximity search
- [x] Filter results and display to user
- [x] Allow more information to be show after interaction

**Comment by DarrachBarneveld** [comment]
Places api and data rendered.
