### ISSUE TITLE
User Story: About Us Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#29]
As a **User**, I can visit the about us page so I can get information about the developer and application

**Acceptance Criteria:**
1. About us page html exists 
2. About us is styled and fully responsive 
3. About contains all relevant information

**Tasks**
- [x] Create aboutus html
- [x] Create styles.css
- [x] Style the page so its fully responsive
- [x] Represent  information about the developers (github/linkedin/photos)
- [x] Write a short mission statement and other copy

**Comment by DarrachBarneveld** [comment]
About us page completed and developers credited
