### ISSUE TITLE
Dev Role: GooglePLacesView

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#31]
As a **developer**, I can have a google places view so that I can fetch relevant location data from google 

**Acceptance Criteria:**
1. A google places view exists
2. Api view is reachable via a url
3. It returns the data in a json format

**Tasks**
- [x] Create a google api view
- [x] Create a url endpoint
- [x] Fetch data from google based on the location data in req.body
- [x] Return data in json format
- [x] Handle any errors with response

**Comment by DarrachBarneveld** [comment]
Issue resolved. Endpoint, view and response created
