### ISSUE TITLE
User Story: Google Places Card

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#32]
As a **User**, I can see a places card so that I can find more info on where to do ai prompt activity

**Acceptance Criteria:**
1. Standardised google places card
2. Card displays all information
3. Card is fully responsive
4. All links work as expected

**Tasks**
- [x] Style a places card
- [x] Ensure the card is responsive
- [x] Have an image as the header
- [x] Display all data in a clean manner
- [x] Install links

**Comment by DarrachBarneveld** [comment]
Card designed and renders all data effectively
