### ISSUE TITLE
Dev Role: Api response in Chunk

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#33]
As a **dev**, I can manipulate Openai response into chunks so that I can stream data without delay to user

**Acceptance Criteria:**
1. AI response data is broken into chunks
2. Chunks are sent to user periodically
3. Chunks are streamed and rendered

**Tasks**
- [x] Create a stream/chunk function
- [x] Return data in a stream, not a solid response
- [x] Render data to UI as it comes in
- [ ]

**Comment by Camelia03** [comment]
I'm not sure what you mean about the Render data to UI . Maybe when you have time, you can give me some more details. :)

**Comment by DarrachBarneveld** [comment]
Chunk stream works as expected. Will not integrate into front end
