### ISSUE TITLE
User Story: Contact Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#34]
As a **User**, I can visit the contact us page so I can give feedback on the app

**Acceptance Criteria:**
1. contact us page html exists 
2. Contact us is styled and fully responsive 
3. A form exists to relay messages
4. Redirects to thank you page

**Tasks**
- [x] Create contactus html
- [x] Style the page so its fully responsive
- [x] Create a form for a user to enter details and message
- [x] Redirect user to thank you page on submission

**Comment by DarrachBarneveld** [comment]
Contact page detailed and links to thankyoupage
