### ISSUE TITLE
Dev Role: Deployment

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#47]
As a **Dev**, I can deploy to heroku or another provider so that my application can be run live

**Acceptance Criteria:**
1. Api is deployed and configured
2. Front end is deployed and is shown as in original 
3. No cors issues exist and front / back are connect
4. 

**Tasks**
- [x] Deploy API to heroku
- [x] Include all config vars
- [x] Deploy front end to heroku/netlify
- [x] Allow correct settings for fetch calls (CORS, Allowed Hosts)
-

**Comment by DarrachBarneveld** [comment]
Site is deployed and live, works as expected
