### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#5]
As a **developer**, I can set up the initial project setup so that all files are configured for work

**Tasks**
- [x] Setup package json
- [x] Install required packages
- [x] Set up base files

**Comment by DarrachBarneveld** [comment]
Initial Project set up completed
