### ISSUE TITLE
User Story: Animations

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#53]
As a **User**, I can see animations to give me a better user experience and emotional response

**Tasks**

- [ ] 1. Create some animations of love hearts
- [ ] 2. Display these hearts on certain pages
- [ ] 3. Create loading animations
- [ ] 4. Create rendering animations

**Comment by DarrachBarneveld** [comment]
Heart animations rendered
