### ISSUE TITLE
Wireframes Homepage

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#6]
**Tasks**
- [x]  Create basic wireframes for homepage
- [x]  Select potential colours 
- [x]  Select potential images

**Comment by DarrachBarneveld** [comment]
Layouts completed. Overall structure planned
