### ISSUE TITLE
Wireframes About us

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#7]
**Tasks**
- [ ]  Create basic wireframes for wireframes
- [ ]  Select potential colours 
- [ ]  Select potential images
