### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#8]
**Tasks**
- [x] Create a colour palette for the site
- [x] Select logo for site 
- [x] Select fonts or general style aesthetic
