### ISSUE TITLE
User Story: AI recommendations

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/cupidai#9]
As a **User**, I can input data so that I can get recommendations based on AI

**Acceptance Criteria:**
1. Input fields are rendered
2. AI recommendations are displayed clearly

**Tasks**
- [x] Create user inputs fields
- [x] Input user data into API calls
- [x] Render API call to UI

**Comment by DarrachBarneveld** [comment]
Basic skeleton of ai prompt is created
